"""Add Bio Column at Info table

Revision ID: 839f489e5bbb
Revises: e46ceb3fe1a8
Create Date: 2026-07-15 20:50:54.965912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839f489e5bbb'
down_revision: Union[str, Sequence[str], None] = 'e46ceb3fe1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('bio', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'bio')
    # ### end Alembic commands ###
