"""Add model Achievement

Revision ID: d5d5da5f712e
Revises: 7d02ad96c726
Create Date: 2026-08-04 18:29:44.205050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d5da5f712e'
down_revision: Union[str, Sequence[str], None] = '7d02ad96c726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('img_url', sa.String(length=1024), nullable=True),
    sa.Column('img_public_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement')
    # ### end Alembic commands ###
