"""Add Info Table

Revision ID: e46ceb3fe1a8
Revises: 63cedacf0aa0
Create Date: 2026-07-15 20:16:53.267651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e46ceb3fe1a8'
down_revision: Union[str, Sequence[str], None] = '63cedacf0aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('hometown', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('major', sa.String(length=30), nullable=False),
    sa.Column('language', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('framework', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_fullname'), 'info', ['fullname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_fullname'), table_name='info')
    op.drop_table('info')
    # ### end Alembic commands ###
